//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.DeliveryNoteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryNoteService.IFoljesedelService")]
    public interface IFoljesedelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/Ping", ReplyAction="http://tempuri.org/IFoljesedelService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/Ping", ReplyAction="http://tempuri.org/IFoljesedelService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetComments", ReplyAction="http://tempuri.org/IFoljesedelService/GetCommentsResponse")]
        string[] GetComments(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetComments", ReplyAction="http://tempuri.org/IFoljesedelService/GetCommentsResponse")]
        System.Threading.Tasks.Task<string[]> GetCommentsAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/Search", ReplyAction="http://tempuri.org/IFoljesedelService/SearchResponse")]
        Gro.Core.DataModels.DeliveryNoteDtos.FoljesedelResponse[] Search(string fabricId, string customerNumber, string articleNumber, string orderNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/Search", ReplyAction="http://tempuri.org/IFoljesedelService/SearchResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.FoljesedelResponse[]> SearchAsync(string fabricId, string customerNumber, string articleNumber, string orderNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetFabrics", ReplyAction="http://tempuri.org/IFoljesedelService/GetFabricsResponse")]
        Gro.Core.DataModels.DeliveryNoteDtos.FabricItemResponse[] GetFabrics(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetFabrics", ReplyAction="http://tempuri.org/IFoljesedelService/GetFabricsResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.FabricItemResponse[]> GetFabricsAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetPDFData", ReplyAction="http://tempuri.org/IFoljesedelService/GetPDFDataResponse")]
        byte[] GetPDFData(string orderNumber, int fabricId, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetPDFData", ReplyAction="http://tempuri.org/IFoljesedelService/GetPDFDataResponse")]
        System.Threading.Tasks.Task<byte[]> GetPDFDataAsync(string orderNumber, int fabricId, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetPDFFile", ReplyAction="http://tempuri.org/IFoljesedelService/GetPDFFileResponse")]
        string GetPDFFile(string orderNumber, int fabricId, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetPDFFile", ReplyAction="http://tempuri.org/IFoljesedelService/GetPDFFileResponse")]
        System.Threading.Tasks.Task<string> GetPDFFileAsync(string orderNumber, int fabricId, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetBulkfoderLeverans", ReplyAction="http://tempuri.org/IFoljesedelService/GetBulkfoderLeveransResponse")]
        Gro.Core.DataModels.DeliveryNoteDtos.BulkfoderLeveransResponse[] GetBulkfoderLeverans(int system, string customerOrderNumber, int rowNumber, int lopnummer, int fabricId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetBulkfoderLeverans", ReplyAction="http://tempuri.org/IFoljesedelService/GetBulkfoderLeveransResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.BulkfoderLeveransResponse[]> GetBulkfoderLeveransAsync(int system, string customerOrderNumber, int rowNumber, int lopnummer, int fabricId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetReceptNumber", ReplyAction="http://tempuri.org/IFoljesedelService/GetReceptNumberResponse")]
        int GetReceptNumber(string receptNumber, string tillvord, int fabricId, int receptVersion, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetReceptNumber", ReplyAction="http://tempuri.org/IFoljesedelService/GetReceptNumberResponse")]
        System.Threading.Tasks.Task<int> GetReceptNumberAsync(string receptNumber, string tillvord, int fabricId, int receptVersion, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetVaruInfoDefault", ReplyAction="http://tempuri.org/IFoljesedelService/GetVaruInfoDefaultResponse")]
        Gro.Core.DataModels.DeliveryNoteDtos.AnalysGruppResponse[] GetVaruInfoDefault(string artikel, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetVaruInfoDefault", ReplyAction="http://tempuri.org/IFoljesedelService/GetVaruInfoDefaultResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.AnalysGruppResponse[]> GetVaruInfoDefaultAsync(string artikel, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetVaruInfo", ReplyAction="http://tempuri.org/IFoljesedelService/GetVaruInfoResponse")]
        string[] GetVaruInfo(int recept, int version, int fabricId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetVaruInfo", ReplyAction="http://tempuri.org/IFoljesedelService/GetVaruInfoResponse")]
        System.Threading.Tasks.Task<string[]> GetVaruInfoAsync(int recept, int version, int fabricId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/IsArtikelType55", ReplyAction="http://tempuri.org/IFoljesedelService/IsArtikelType55Response")]
        bool IsArtikelType55(string articleNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/IsArtikelType55", ReplyAction="http://tempuri.org/IFoljesedelService/IsArtikelType55Response")]
        System.Threading.Tasks.Task<bool> IsArtikelType55Async(string articleNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetDurabilityText4", ReplyAction="http://tempuri.org/IFoljesedelService/GetDurabilityText4Response")]
        string[] GetDurabilityText4(int customerOrderNumber, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetDurabilityText4", ReplyAction="http://tempuri.org/IFoljesedelService/GetDurabilityText4Response")]
        System.Threading.Tasks.Task<string[]> GetDurabilityText4Async(int customerOrderNumber, int rowNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetDurabilityText3", ReplyAction="http://tempuri.org/IFoljesedelService/GetDurabilityText3Response")]
        string[] GetDurabilityText3(string customerOrderNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoljesedelService/GetDurabilityText3", ReplyAction="http://tempuri.org/IFoljesedelService/GetDurabilityText3Response")]
        System.Threading.Tasks.Task<string[]> GetDurabilityText3Async(string customerOrderNumber, string ticket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFoljesedelServiceChannel : Gro.Infrastructure.Data.DeliveryNoteService.IFoljesedelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FoljesedelServiceClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.DeliveryNoteService.IFoljesedelService>, Gro.Infrastructure.Data.DeliveryNoteService.IFoljesedelService {
        
        public FoljesedelServiceClient() {
        }
        
        public FoljesedelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FoljesedelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoljesedelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FoljesedelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public string[] GetComments(string ticket) {
            return base.Channel.GetComments(ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCommentsAsync(string ticket) {
            return base.Channel.GetCommentsAsync(ticket);
        }
        
        public Gro.Core.DataModels.DeliveryNoteDtos.FoljesedelResponse[] Search(string fabricId, string customerNumber, string articleNumber, string orderNumber, string ticket) {
            return base.Channel.Search(fabricId, customerNumber, articleNumber, orderNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.FoljesedelResponse[]> SearchAsync(string fabricId, string customerNumber, string articleNumber, string orderNumber, string ticket) {
            return base.Channel.SearchAsync(fabricId, customerNumber, articleNumber, orderNumber, ticket);
        }
        
        public Gro.Core.DataModels.DeliveryNoteDtos.FabricItemResponse[] GetFabrics(string ticket) {
            return base.Channel.GetFabrics(ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.FabricItemResponse[]> GetFabricsAsync(string ticket) {
            return base.Channel.GetFabricsAsync(ticket);
        }
        
        public byte[] GetPDFData(string orderNumber, int fabricId, int rowNumber, string ticket) {
            return base.Channel.GetPDFData(orderNumber, fabricId, rowNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<byte[]> GetPDFDataAsync(string orderNumber, int fabricId, int rowNumber, string ticket) {
            return base.Channel.GetPDFDataAsync(orderNumber, fabricId, rowNumber, ticket);
        }
        
        public string GetPDFFile(string orderNumber, int fabricId, int rowNumber, string ticket) {
            return base.Channel.GetPDFFile(orderNumber, fabricId, rowNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<string> GetPDFFileAsync(string orderNumber, int fabricId, int rowNumber, string ticket) {
            return base.Channel.GetPDFFileAsync(orderNumber, fabricId, rowNumber, ticket);
        }
        
        public Gro.Core.DataModels.DeliveryNoteDtos.BulkfoderLeveransResponse[] GetBulkfoderLeverans(int system, string customerOrderNumber, int rowNumber, int lopnummer, int fabricId, string ticket) {
            return base.Channel.GetBulkfoderLeverans(system, customerOrderNumber, rowNumber, lopnummer, fabricId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.BulkfoderLeveransResponse[]> GetBulkfoderLeveransAsync(int system, string customerOrderNumber, int rowNumber, int lopnummer, int fabricId, string ticket) {
            return base.Channel.GetBulkfoderLeveransAsync(system, customerOrderNumber, rowNumber, lopnummer, fabricId, ticket);
        }
        
        public int GetReceptNumber(string receptNumber, string tillvord, int fabricId, int receptVersion, string ticket) {
            return base.Channel.GetReceptNumber(receptNumber, tillvord, fabricId, receptVersion, ticket);
        }
        
        public System.Threading.Tasks.Task<int> GetReceptNumberAsync(string receptNumber, string tillvord, int fabricId, int receptVersion, string ticket) {
            return base.Channel.GetReceptNumberAsync(receptNumber, tillvord, fabricId, receptVersion, ticket);
        }
        
        public Gro.Core.DataModels.DeliveryNoteDtos.AnalysGruppResponse[] GetVaruInfoDefault(string artikel, string ticket) {
            return base.Channel.GetVaruInfoDefault(artikel, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.DeliveryNoteDtos.AnalysGruppResponse[]> GetVaruInfoDefaultAsync(string artikel, string ticket) {
            return base.Channel.GetVaruInfoDefaultAsync(artikel, ticket);
        }
        
        public string[] GetVaruInfo(int recept, int version, int fabricId, string ticket) {
            return base.Channel.GetVaruInfo(recept, version, fabricId, ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetVaruInfoAsync(int recept, int version, int fabricId, string ticket) {
            return base.Channel.GetVaruInfoAsync(recept, version, fabricId, ticket);
        }
        
        public bool IsArtikelType55(string articleNumber, string ticket) {
            return base.Channel.IsArtikelType55(articleNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<bool> IsArtikelType55Async(string articleNumber, string ticket) {
            return base.Channel.IsArtikelType55Async(articleNumber, ticket);
        }
        
        public string[] GetDurabilityText4(int customerOrderNumber, int rowNumber, string ticket) {
            return base.Channel.GetDurabilityText4(customerOrderNumber, rowNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDurabilityText4Async(int customerOrderNumber, int rowNumber, string ticket) {
            return base.Channel.GetDurabilityText4Async(customerOrderNumber, rowNumber, ticket);
        }
        
        public string[] GetDurabilityText3(string customerOrderNumber, string ticket) {
            return base.Channel.GetDurabilityText3(customerOrderNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetDurabilityText3Async(string customerOrderNumber, string ticket) {
            return base.Channel.GetDurabilityText3Async(customerOrderNumber, ticket);
        }
    }
}
