//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.MachineRemoveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId", ConfigurationName="MachineRemoveService.deleteMachineForCustomerId_PortType")]
    public interface deleteMachineForCustomerId_PortType {
        
        // CODEGEN: Parameter 'individSaveResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="LMMA_MAS_C4_ws_deleteMachineForCustomerId_Binder_deleteMachineForCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="individSaveResponse")]
        Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse deleteMachineForCustomerId(Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LMMA_MAS_C4_ws_deleteMachineForCustomerId_Binder_deleteMachineForCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse> deleteMachineForCustomerIdAsync(Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId")]
    public partial class individSaveOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IOEnvelope iOEnvelopeField;
        
        private string versionField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public IOEnvelope IOEnvelope {
            get {
                return this.iOEnvelopeField;
            }
            set {
                this.iOEnvelopeField = value;
                this.RaisePropertyChanged("IOEnvelope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId")]
    public partial class IOEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FunctionStatus functionStatusField;
        
        private Data dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public FunctionStatus FunctionStatus {
            get {
                return this.functionStatusField;
            }
            set {
                this.functionStatusField = value;
                this.RaisePropertyChanged("FunctionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Data Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId")]
    public partial class FunctionStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string textField;
        
        private string userTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string UserText {
            get {
                return this.userTextField;
            }
            set {
                this.userTextField = value;
                this.RaisePropertyChanged("UserText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMachineForCustomerId", WrapperNamespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId", IsWrapped=true)]
    public partial class deleteMachineForCustomerIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ID;
        
        public deleteMachineForCustomerIdRequest() {
        }
        
        public deleteMachineForCustomerIdRequest(string ID) {
            this.ID = ID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deleteMachineForCustomerIdResponse", WrapperNamespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId", IsWrapped=true)]
    public partial class deleteMachineForCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sci.lantmannen.com/LMMA_MAS_C4.ws:deleteMachineForCustomerId", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Gro.Infrastructure.Data.MachineRemoveService.individSaveOutput individSaveResponse;
        
        public deleteMachineForCustomerIdResponse() {
        }
        
        public deleteMachineForCustomerIdResponse(Gro.Infrastructure.Data.MachineRemoveService.individSaveOutput individSaveResponse) {
            this.individSaveResponse = individSaveResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface deleteMachineForCustomerId_PortTypeChannel : Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class deleteMachineForCustomerId_PortTypeClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType>, Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType {
        
        public deleteMachineForCustomerId_PortTypeClient() {
        }
        
        public deleteMachineForCustomerId_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public deleteMachineForCustomerId_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public deleteMachineForCustomerId_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public deleteMachineForCustomerId_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType.deleteMachineForCustomerId(Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest request) {
            return base.Channel.deleteMachineForCustomerId(request);
        }
        
        public Gro.Infrastructure.Data.MachineRemoveService.individSaveOutput deleteMachineForCustomerId(string ID) {
            Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest inValue = new Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest();
            inValue.ID = ID;
            Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse retVal = ((Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType)(this)).deleteMachineForCustomerId(inValue);
            return retVal.individSaveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse> Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType.deleteMachineForCustomerIdAsync(Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest request) {
            return base.Channel.deleteMachineForCustomerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdResponse> deleteMachineForCustomerIdAsync(string ID) {
            Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest inValue = new Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerIdRequest();
            inValue.ID = ID;
            return ((Gro.Infrastructure.Data.MachineRemoveService.deleteMachineForCustomerId_PortType)(this)).deleteMachineForCustomerIdAsync(inValue);
        }
    }
}
