//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.MachineAddNewServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", ConfigurationName="MachineAddNewServer.updateMachineForCustomerId_PortType")]
    public interface updateMachineForCustomerId_PortType {
        
        // CODEGEN: Parameter 'individSaveResponse' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="LMMA_MAS_C4_ws_updateMachineForCustomerId_Binder_updateMachineForCustomerId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="individSaveResponse")]
        Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse updateMachineForCustomerId(Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="LMMA_MAS_C4_ws_updateMachineForCustomerId_Binder_updateMachineForCustomerId", ReplyAction="*")]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse> updateMachineForCustomerIdAsync(Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId")]
    public partial class individSaveOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private IOEnvelope iOEnvelopeField;
        
        private string versionField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public IOEnvelope IOEnvelope {
            get {
                return this.iOEnvelopeField;
            }
            set {
                this.iOEnvelopeField = value;
                this.RaisePropertyChanged("IOEnvelope");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
                this.RaisePropertyChanged("encoding");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId")]
    public partial class IOEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FunctionStatus functionStatusField;
        
        private Data dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public FunctionStatus FunctionStatus {
            get {
                return this.functionStatusField;
            }
            set {
                this.functionStatusField = value;
                this.RaisePropertyChanged("FunctionStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public Data Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId")]
    public partial class FunctionStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusField;
        
        private string textField;
        
        private string userTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string UserText {
            get {
                return this.userTextField;
            }
            set {
                this.userTextField = value;
                this.RaisePropertyChanged("UserText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId")]
    public partial class Data : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMachineForCustomerId", WrapperNamespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", IsWrapped=true)]
    public partial class updateMachineForCustomerIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string ID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string OWNER;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string BRAND;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DESCRBRAND;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string MODEL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string DESCRMODEL;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string INDTYPE;
        
        public updateMachineForCustomerIdRequest() {
        }
        
        public updateMachineForCustomerIdRequest(string ID, string OWNER, string BRAND, string DESCRBRAND, string MODEL, string DESCRMODEL, string INDTYPE) {
            this.ID = ID;
            this.OWNER = OWNER;
            this.BRAND = BRAND;
            this.DESCRBRAND = DESCRBRAND;
            this.MODEL = MODEL;
            this.DESCRMODEL = DESCRMODEL;
            this.INDTYPE = INDTYPE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateMachineForCustomerIdResponse", WrapperNamespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", IsWrapped=true)]
    public partial class updateMachineForCustomerIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://169.254.234.32/LMMA_MAS_C4.ws:updateMachineForCustomerId", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public Gro.Infrastructure.Data.MachineAddNewServer.individSaveOutput individSaveResponse;
        
        public updateMachineForCustomerIdResponse() {
        }
        
        public updateMachineForCustomerIdResponse(Gro.Infrastructure.Data.MachineAddNewServer.individSaveOutput individSaveResponse) {
            this.individSaveResponse = individSaveResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface updateMachineForCustomerId_PortTypeChannel : Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class updateMachineForCustomerId_PortTypeClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType>, Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType {
        
        public updateMachineForCustomerId_PortTypeClient() {
        }
        
        public updateMachineForCustomerId_PortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public updateMachineForCustomerId_PortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public updateMachineForCustomerId_PortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public updateMachineForCustomerId_PortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType.updateMachineForCustomerId(Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest request) {
            return base.Channel.updateMachineForCustomerId(request);
        }
        
        public Gro.Infrastructure.Data.MachineAddNewServer.individSaveOutput updateMachineForCustomerId(string ID, string OWNER, string BRAND, string DESCRBRAND, string MODEL, string DESCRMODEL, string INDTYPE) {
            Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest inValue = new Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest();
            inValue.ID = ID;
            inValue.OWNER = OWNER;
            inValue.BRAND = BRAND;
            inValue.DESCRBRAND = DESCRBRAND;
            inValue.MODEL = MODEL;
            inValue.DESCRMODEL = DESCRMODEL;
            inValue.INDTYPE = INDTYPE;
            Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse retVal = ((Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType)(this)).updateMachineForCustomerId(inValue);
            return retVal.individSaveResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse> Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType.updateMachineForCustomerIdAsync(Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest request) {
            return base.Channel.updateMachineForCustomerIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdResponse> updateMachineForCustomerIdAsync(string ID, string OWNER, string BRAND, string DESCRBRAND, string MODEL, string DESCRMODEL, string INDTYPE) {
            Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest inValue = new Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerIdRequest();
            inValue.ID = ID;
            inValue.OWNER = OWNER;
            inValue.BRAND = BRAND;
            inValue.DESCRBRAND = DESCRBRAND;
            inValue.MODEL = MODEL;
            inValue.DESCRMODEL = DESCRMODEL;
            inValue.INDTYPE = INDTYPE;
            return ((Gro.Infrastructure.Data.MachineAddNewServer.updateMachineForCustomerId_PortType)(this)).updateMachineForCustomerIdAsync(inValue);
        }
    }
}
