//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.LogiWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LantmannenLantbrukWcfException", Namespace="http://lantmannenlantbruk.se/1.0.0.0/")]
    [System.SerializableAttribute()]
    public partial class LantmannenLantbrukWcfException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Gro.Infrastructure.Data.LogiWebService.WcfErrorCode CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Gro.Infrastructure.Data.LogiWebService.WcfErrorCode Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WcfErrorCode", Namespace="http://schemas.datacontract.org/2004/07/WcfCommon")]
    public enum WcfErrorCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotFound = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TicketNotValid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnKnownError = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrderStatus", Namespace="http://lantmannenlantbruk.se/1.0.0.0/")]
    [System.SerializableAttribute()]
    public partial class OrderStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoadingPlace", Namespace="http://lantmannenlantbruk.se/1.0.0.0/")]
    [System.SerializableAttribute()]
    public partial class LoadingPlace : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrorageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrorageNumber {
            get {
                return this.StrorageNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.StrorageNumberField, value) != true)) {
                    this.StrorageNumberField = value;
                    this.RaisePropertyChanged("StrorageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReportItem", Namespace="http://schemas.datacontract.org/2004/07/LogiWebServiceInt.Models")]
    [System.SerializableAttribute()]
    public partial class ReportItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerOrderNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerRowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelAddress3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelAddress4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelCustNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelCustNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DelDescriptionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveredQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromStorageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromStorageNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeveransdatumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderIdMxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderRowNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderedQuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderrowStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderrowStatusNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlannedCarRegistationNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> PlannedDeliveryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShipmentIdMXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiloNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransportPayerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TripNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerOrderNumber {
            get {
                return this.CustomerOrderNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerOrderNumberField, value) != true)) {
                    this.CustomerOrderNumberField = value;
                    this.RaisePropertyChanged("CustomerOrderNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerRowNumber {
            get {
                return this.CustomerRowNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerRowNumberField, value) != true)) {
                    this.CustomerRowNumberField = value;
                    this.RaisePropertyChanged("CustomerRowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelAddress1 {
            get {
                return this.DelAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.DelAddress1Field, value) != true)) {
                    this.DelAddress1Field = value;
                    this.RaisePropertyChanged("DelAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelAddress2 {
            get {
                return this.DelAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.DelAddress2Field, value) != true)) {
                    this.DelAddress2Field = value;
                    this.RaisePropertyChanged("DelAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelAddress3 {
            get {
                return this.DelAddress3Field;
            }
            set {
                if ((object.ReferenceEquals(this.DelAddress3Field, value) != true)) {
                    this.DelAddress3Field = value;
                    this.RaisePropertyChanged("DelAddress3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelAddress4 {
            get {
                return this.DelAddress4Field;
            }
            set {
                if ((object.ReferenceEquals(this.DelAddress4Field, value) != true)) {
                    this.DelAddress4Field = value;
                    this.RaisePropertyChanged("DelAddress4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelCustName {
            get {
                return this.DelCustNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DelCustNameField, value) != true)) {
                    this.DelCustNameField = value;
                    this.RaisePropertyChanged("DelCustName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelCustNo {
            get {
                return this.DelCustNoField;
            }
            set {
                if ((object.ReferenceEquals(this.DelCustNoField, value) != true)) {
                    this.DelCustNoField = value;
                    this.RaisePropertyChanged("DelCustNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DelDescriptionNumber {
            get {
                return this.DelDescriptionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.DelDescriptionNumberField, value) != true)) {
                    this.DelDescriptionNumberField = value;
                    this.RaisePropertyChanged("DelDescriptionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveredQuantity {
            get {
                return this.DeliveredQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveredQuantityField, value) != true)) {
                    this.DeliveredQuantityField = value;
                    this.RaisePropertyChanged("DeliveredQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromStorageId {
            get {
                return this.FromStorageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.FromStorageIdField, value) != true)) {
                    this.FromStorageIdField = value;
                    this.RaisePropertyChanged("FromStorageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromStorageName {
            get {
                return this.FromStorageNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FromStorageNameField, value) != true)) {
                    this.FromStorageNameField = value;
                    this.RaisePropertyChanged("FromStorageName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemName {
            get {
                return this.ItemNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNameField, value) != true)) {
                    this.ItemNameField = value;
                    this.RaisePropertyChanged("ItemName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leveransdatum {
            get {
                return this.LeveransdatumField;
            }
            set {
                if ((object.ReferenceEquals(this.LeveransdatumField, value) != true)) {
                    this.LeveransdatumField = value;
                    this.RaisePropertyChanged("Leveransdatum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderIdMx {
            get {
                return this.OrderIdMxField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderIdMxField, value) != true)) {
                    this.OrderIdMxField = value;
                    this.RaisePropertyChanged("OrderIdMx");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderRowNumber {
            get {
                return this.OrderRowNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderRowNumberField, value) != true)) {
                    this.OrderRowNumberField = value;
                    this.RaisePropertyChanged("OrderRowNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderedQuantity {
            get {
                return this.OrderedQuantityField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderedQuantityField, value) != true)) {
                    this.OrderedQuantityField = value;
                    this.RaisePropertyChanged("OrderedQuantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderrowStatus {
            get {
                return this.OrderrowStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderrowStatusField, value) != true)) {
                    this.OrderrowStatusField = value;
                    this.RaisePropertyChanged("OrderrowStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderrowStatusName {
            get {
                return this.OrderrowStatusNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderrowStatusNameField, value) != true)) {
                    this.OrderrowStatusNameField = value;
                    this.RaisePropertyChanged("OrderrowStatusName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlannedCarRegistationNumber {
            get {
                return this.PlannedCarRegistationNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PlannedCarRegistationNumberField, value) != true)) {
                    this.PlannedCarRegistationNumberField = value;
                    this.RaisePropertyChanged("PlannedCarRegistationNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> PlannedDeliveryDate {
            get {
                return this.PlannedDeliveryDateField;
            }
            set {
                if ((this.PlannedDeliveryDateField.Equals(value) != true)) {
                    this.PlannedDeliveryDateField = value;
                    this.RaisePropertyChanged("PlannedDeliveryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShipmentIdMX {
            get {
                return this.ShipmentIdMXField;
            }
            set {
                if ((object.ReferenceEquals(this.ShipmentIdMXField, value) != true)) {
                    this.ShipmentIdMXField = value;
                    this.RaisePropertyChanged("ShipmentIdMX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiloNumber {
            get {
                return this.SiloNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SiloNumberField, value) != true)) {
                    this.SiloNumberField = value;
                    this.RaisePropertyChanged("SiloNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransportPayer {
            get {
                return this.TransportPayerField;
            }
            set {
                if ((object.ReferenceEquals(this.TransportPayerField, value) != true)) {
                    this.TransportPayerField = value;
                    this.RaisePropertyChanged("TransportPayer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TripNumber {
            get {
                return this.TripNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TripNumberField, value) != true)) {
                    this.TripNumberField = value;
                    this.RaisePropertyChanged("TripNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://lantmannenlantbruk.se/1.0.0.0/", ConfigurationName="LogiWebService.ILogiWebService")]
    public interface ILogiWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/Ping", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/Ping", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerNumberRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerNumberLantma" +
            "nnenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByCustomerNumber(string customerNumber, System.DateTime fromdate, System.DateTime todate, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerNumberRespon" +
            "se")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByCustomerNumberAsync(string customerNumber, System.DateTime fromdate, System.DateTime todate, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByShipmentIdMX", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByShipmentIdMXResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByShipmentIdMXLantmann" +
            "enLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByShipmentIdMX(int shipmentIdMX, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByShipmentIdMX", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByShipmentIdMXResponse" +
            "")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByShipmentIdMXAsync(int shipmentIdMX, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByOrderNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByOrderNumberLantmanne" +
            "nLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByOrderNumber(string orderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByOrderNumberResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByOrderNumberAsync(string orderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerOrderNumberR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerOrderNumberL" +
            "antmannenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByCustomerOrderNumber(string customerOrderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCustomerOrderNumberR" +
            "esponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByCustomerOrderNumberAsync(string customerOrderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByWaybillNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByWaybillNumberRespons" +
            "e")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByWaybillNumberLantman" +
            "nenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByWaybillNumber(string waybillNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByWaybillNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByWaybillNumberRespons" +
            "e")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByWaybillNumberAsync(string waybillNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCarrier", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCarrierResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCarrierLantmannenLan" +
            "tbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByCarrier(string carrier, string currentUsersCustomerNumber, System.DateTime fromdate, System.DateTime todate, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCarrier", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/SearchByCarrierResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByCarrierAsync(string carrier, string currentUsersCustomerNumber, System.DateTime fromdate, System.DateTime todate, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderRowsByShipmentIdMX", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderRowsByShipmentIdMXRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderRowsByShipmentIdMXLa" +
            "ntmannenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.OrderRowResponse[] GetOrderRowsByShipmentIdMX(int shipmentIdMX, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderRowsByShipmentIdMX", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderRowsByShipmentIdMXRe" +
            "sponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> GetOrderRowsByShipmentIdMXAsync(int shipmentIdMX, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByOrderNumberRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByOrderNumberLa" +
            "ntmannenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.ShipmentResponse[] GetShipmentsdByOrderNumber(string orderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByOrderNumber", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByOrderNumberRe" +
            "sponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> GetShipmentsdByOrderNumberAsync(string orderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByCustomerOrder" +
            "Number", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByCustomerOrder" +
            "NumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByCustomerOrder" +
            "NumberLantmannenLantbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.ShipmentResponse[] GetShipmentsdByCustomerOrderNumber(string customerOrderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByCustomerOrder" +
            "Number", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetShipmentsdByCustomerOrder" +
            "NumberResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> GetShipmentsdByCustomerOrderNumberAsync(string customerOrderNumber, string currentUsersCustomerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetCarriers", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetCarriersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetCarriersLantmannenLantbru" +
            "kWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        string[] GetCarriers(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetCarriers", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetCarriersResponse")]
        System.Threading.Tasks.Task<string[]> GetCarriersAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetAnnoncements", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetAnnoncementsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetAnnoncementsLantmannenLan" +
            "tbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Core.DataModels.SearchTransport.Annoncement[] GetAnnoncements(int orderRowId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetAnnoncements", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetAnnoncementsResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.Annoncement[]> GetAnnoncementsAsync(int orderRowId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderStatus", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderStatusResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderStatusLantmannenLant" +
            "brukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Infrastructure.Data.LogiWebService.OrderStatus[] GetOrderStatus(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderStatus", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetOrderStatusResponse")]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.OrderStatus[]> GetOrderStatusAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetLoadingPlaces", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetLoadingPlacesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetLoadingPlacesLantmannenLa" +
            "ntbrukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Infrastructure.Data.LogiWebService.LoadingPlace[] GetLoadingPlaces(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetLoadingPlaces", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetLoadingPlacesResponse")]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.LoadingPlace[]> GetLoadingPlacesAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetReportData", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetReportDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetReportDataLantmannenLantb" +
            "rukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        Gro.Infrastructure.Data.LogiWebService.ReportItem[] GetReportData(string fromDate, string toDate, string transportPayer, System.Nullable<int> fromStorageId, System.Nullable<int> orderRowStatus, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetReportData", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetReportDataResponse")]
        System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.ReportItem[]> GetReportDataAsync(string fromDate, string toDate, string transportPayer, System.Nullable<int> fromStorageId, System.Nullable<int> orderRowStatus, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetEsalesUrl", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetEsalesUrlResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Gro.Infrastructure.Data.LogiWebService.LantmannenLantbrukWcfException), Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetEsalesUrlLantmannenLantbr" +
            "ukWcfExceptionFault", Name="LantmannenLantbrukWcfException")]
        string GetEsalesUrl(string customerNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetEsalesUrl", ReplyAction="http://lantmannenlantbruk.se/1.0.0.0/ILogiWebService/GetEsalesUrlResponse")]
        System.Threading.Tasks.Task<string> GetEsalesUrlAsync(string customerNumber, string ticket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogiWebServiceChannel : Gro.Infrastructure.Data.LogiWebService.ILogiWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogiWebServiceClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.LogiWebService.ILogiWebService>, Gro.Infrastructure.Data.LogiWebService.ILogiWebService {
        
        public LogiWebServiceClient() {
        }
        
        public LogiWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogiWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogiWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogiWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByCustomerNumber(string customerNumber, System.DateTime fromdate, System.DateTime todate, string ticket) {
            return base.Channel.SearchByCustomerNumber(customerNumber, fromdate, todate, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByCustomerNumberAsync(string customerNumber, System.DateTime fromdate, System.DateTime todate, string ticket) {
            return base.Channel.SearchByCustomerNumberAsync(customerNumber, fromdate, todate, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByShipmentIdMX(int shipmentIdMX, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByShipmentIdMX(shipmentIdMX, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByShipmentIdMXAsync(int shipmentIdMX, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByShipmentIdMXAsync(shipmentIdMX, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByOrderNumber(string orderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByOrderNumber(orderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByOrderNumberAsync(string orderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByOrderNumberAsync(orderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.OrderRowResponse[] SearchByCustomerOrderNumber(string customerOrderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByCustomerOrderNumber(customerOrderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> SearchByCustomerOrderNumberAsync(string customerOrderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByCustomerOrderNumberAsync(customerOrderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByWaybillNumber(string waybillNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByWaybillNumber(waybillNumber, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByWaybillNumberAsync(string waybillNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.SearchByWaybillNumberAsync(waybillNumber, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.ShipmentResponse[] SearchByCarrier(string carrier, string currentUsersCustomerNumber, System.DateTime fromdate, System.DateTime todate, string ticket) {
            return base.Channel.SearchByCarrier(carrier, currentUsersCustomerNumber, fromdate, todate, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> SearchByCarrierAsync(string carrier, string currentUsersCustomerNumber, System.DateTime fromdate, System.DateTime todate, string ticket) {
            return base.Channel.SearchByCarrierAsync(carrier, currentUsersCustomerNumber, fromdate, todate, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.OrderRowResponse[] GetOrderRowsByShipmentIdMX(int shipmentIdMX, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetOrderRowsByShipmentIdMX(shipmentIdMX, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.OrderRowResponse[]> GetOrderRowsByShipmentIdMXAsync(int shipmentIdMX, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetOrderRowsByShipmentIdMXAsync(shipmentIdMX, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.ShipmentResponse[] GetShipmentsdByOrderNumber(string orderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetShipmentsdByOrderNumber(orderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> GetShipmentsdByOrderNumberAsync(string orderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetShipmentsdByOrderNumberAsync(orderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.ShipmentResponse[] GetShipmentsdByCustomerOrderNumber(string customerOrderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetShipmentsdByCustomerOrderNumber(customerOrderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.ShipmentResponse[]> GetShipmentsdByCustomerOrderNumberAsync(string customerOrderNumber, string currentUsersCustomerNumber, string ticket) {
            return base.Channel.GetShipmentsdByCustomerOrderNumberAsync(customerOrderNumber, currentUsersCustomerNumber, ticket);
        }
        
        public string[] GetCarriers(string ticket) {
            return base.Channel.GetCarriers(ticket);
        }
        
        public System.Threading.Tasks.Task<string[]> GetCarriersAsync(string ticket) {
            return base.Channel.GetCarriersAsync(ticket);
        }
        
        public Gro.Core.DataModels.SearchTransport.Annoncement[] GetAnnoncements(int orderRowId, string ticket) {
            return base.Channel.GetAnnoncements(orderRowId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.SearchTransport.Annoncement[]> GetAnnoncementsAsync(int orderRowId, string ticket) {
            return base.Channel.GetAnnoncementsAsync(orderRowId, ticket);
        }
        
        public Gro.Infrastructure.Data.LogiWebService.OrderStatus[] GetOrderStatus(string ticket) {
            return base.Channel.GetOrderStatus(ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.OrderStatus[]> GetOrderStatusAsync(string ticket) {
            return base.Channel.GetOrderStatusAsync(ticket);
        }
        
        public Gro.Infrastructure.Data.LogiWebService.LoadingPlace[] GetLoadingPlaces(string ticket) {
            return base.Channel.GetLoadingPlaces(ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.LoadingPlace[]> GetLoadingPlacesAsync(string ticket) {
            return base.Channel.GetLoadingPlacesAsync(ticket);
        }
        
        public Gro.Infrastructure.Data.LogiWebService.ReportItem[] GetReportData(string fromDate, string toDate, string transportPayer, System.Nullable<int> fromStorageId, System.Nullable<int> orderRowStatus, string ticket) {
            return base.Channel.GetReportData(fromDate, toDate, transportPayer, fromStorageId, orderRowStatus, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Infrastructure.Data.LogiWebService.ReportItem[]> GetReportDataAsync(string fromDate, string toDate, string transportPayer, System.Nullable<int> fromStorageId, System.Nullable<int> orderRowStatus, string ticket) {
            return base.Channel.GetReportDataAsync(fromDate, toDate, transportPayer, fromStorageId, orderRowStatus, ticket);
        }
        
        public string GetEsalesUrl(string customerNumber, string ticket) {
            return base.Channel.GetEsalesUrl(customerNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<string> GetEsalesUrlAsync(string customerNumber, string ticket) {
            return base.Channel.GetEsalesUrlAsync(customerNumber, ticket);
        }
    }
}
