//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.AgreementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgreementService.IAgreementService")]
    public interface IAgreementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/Ping", ReplyAction="http://tempuri.org/IAgreementService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/Ping", ReplyAction="http://tempuri.org/IAgreementService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetMyOpenAgreements", ReplyAction="http://tempuri.org/IAgreementService/GetMyOpenAgreementsResponse")]
        Gro.Core.DataModels.AgreementDtos.Agreement[] GetMyOpenAgreements(string customerNr, int rowCount, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetMyOpenAgreements", ReplyAction="http://tempuri.org/IAgreementService/GetMyOpenAgreementsResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetMyOpenAgreementsAsync(string customerNr, int rowCount, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetMyOpenSeedAgreements", ReplyAction="http://tempuri.org/IAgreementService/GetMyOpenSeedAgreementsResponse")]
        Gro.Core.DataModels.AgreementDtos.SeedAssurance[] GetMyOpenSeedAgreements(string customerNr, int rowCount, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetMyOpenSeedAgreements", ReplyAction="http://tempuri.org/IAgreementService/GetMyOpenSeedAgreementsResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance[]> GetMyOpenSeedAgreementsAsync(string customerNr, int rowCount, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetSeedAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetSeedAgreementListResponse")]
        Gro.Core.DataModels.AgreementDtos.SeedAssurance[] GetSeedAgreementList(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetSeedAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetSeedAgreementListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance[]> GetSeedAgreementListAsync(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetSeedAgreement", ReplyAction="http://tempuri.org/IAgreementService/GetSeedAgreementResponse")]
        Gro.Core.DataModels.AgreementDtos.SeedAssurance GetSeedAgreement(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetSeedAgreement", ReplyAction="http://tempuri.org/IAgreementService/GetSeedAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance> GetSeedAgreementAsync(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmSampleList", ReplyAction="http://tempuri.org/IAgreementService/GetFarmSampleListResponse")]
        Gro.Core.DataModels.AgreementDtos.FarmSample[] GetFarmSampleList(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmSampleList", ReplyAction="http://tempuri.org/IAgreementService/GetFarmSampleListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.FarmSample[]> GetFarmSampleListAsync(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmSample", ReplyAction="http://tempuri.org/IAgreementService/GetFarmSampleResponse")]
        Gro.Core.DataModels.AgreementDtos.FarmSample GetFarmSample(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmSample", ReplyAction="http://tempuri.org/IAgreementService/GetFarmSampleResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.FarmSample> GetFarmSampleAsync(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetPriceHedgingList", ReplyAction="http://tempuri.org/IAgreementService/GetPriceHedgingListResponse")]
        Gro.Core.DataModels.AgreementDtos.PriceHedging[] GetPriceHedgingList(string supplier, string agreementNo, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetPriceHedgingList", ReplyAction="http://tempuri.org/IAgreementService/GetPriceHedgingListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.PriceHedging[]> GetPriceHedgingListAsync(string supplier, string agreementNo, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetPriceHedging", ReplyAction="http://tempuri.org/IAgreementService/GetPriceHedgingResponse")]
        Gro.Core.DataModels.AgreementDtos.PriceHedging GetPriceHedging(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetPriceHedging", ReplyAction="http://tempuri.org/IAgreementService/GetPriceHedgingResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.PriceHedging> GetPriceHedgingAsync(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetAgreementListResponse")]
        Gro.Core.DataModels.AgreementDtos.Agreement[] GetAgreementList(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetAgreementListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetAgreementListAsync(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmingAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetFarmingAgreementListResponse")]
        Gro.Core.DataModels.AgreementDtos.Agreement[] GetFarmingAgreementList(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetFarmingAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetFarmingAgreementListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetFarmingAgreementListAsync(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetAgreement", ReplyAction="http://tempuri.org/IAgreementService/GetAgreementResponse")]
        Gro.Core.DataModels.AgreementDtos.Agreement GetAgreement(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetAgreement", ReplyAction="http://tempuri.org/IAgreementService/GetAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement> GetAgreementAsync(string supplier, string agreementNumber, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetDryAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetDryAgreementListResponse")]
        Gro.Core.DataModels.AgreementDtos.DryAgreement[] GetDryAgreementList(string supplier, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgreementService/GetDryAgreementList", ReplyAction="http://tempuri.org/IAgreementService/GetDryAgreementListResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.DryAgreement[]> GetDryAgreementListAsync(string supplier, string ticket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgreementServiceChannel : Gro.Infrastructure.Data.AgreementService.IAgreementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgreementServiceClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.AgreementService.IAgreementService>, Gro.Infrastructure.Data.AgreementService.IAgreementService {
        
        public AgreementServiceClient() {
        }
        
        public AgreementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgreementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgreementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgreementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public Gro.Core.DataModels.AgreementDtos.Agreement[] GetMyOpenAgreements(string customerNr, int rowCount, string ticket) {
            return base.Channel.GetMyOpenAgreements(customerNr, rowCount, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetMyOpenAgreementsAsync(string customerNr, int rowCount, string ticket) {
            return base.Channel.GetMyOpenAgreementsAsync(customerNr, rowCount, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.SeedAssurance[] GetMyOpenSeedAgreements(string customerNr, int rowCount, string ticket) {
            return base.Channel.GetMyOpenSeedAgreements(customerNr, rowCount, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance[]> GetMyOpenSeedAgreementsAsync(string customerNr, int rowCount, string ticket) {
            return base.Channel.GetMyOpenSeedAgreementsAsync(customerNr, rowCount, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.SeedAssurance[] GetSeedAgreementList(string supplier, string ticket) {
            return base.Channel.GetSeedAgreementList(supplier, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance[]> GetSeedAgreementListAsync(string supplier, string ticket) {
            return base.Channel.GetSeedAgreementListAsync(supplier, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.SeedAssurance GetSeedAgreement(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetSeedAgreement(supplier, agreementNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.SeedAssurance> GetSeedAgreementAsync(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetSeedAgreementAsync(supplier, agreementNumber, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.FarmSample[] GetFarmSampleList(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetFarmSampleList(supplier, agreementNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.FarmSample[]> GetFarmSampleListAsync(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetFarmSampleListAsync(supplier, agreementNumber, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.FarmSample GetFarmSample(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetFarmSample(supplier, agreementNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.FarmSample> GetFarmSampleAsync(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetFarmSampleAsync(supplier, agreementNumber, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.PriceHedging[] GetPriceHedgingList(string supplier, string agreementNo, string ticket) {
            return base.Channel.GetPriceHedgingList(supplier, agreementNo, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.PriceHedging[]> GetPriceHedgingListAsync(string supplier, string agreementNo, string ticket) {
            return base.Channel.GetPriceHedgingListAsync(supplier, agreementNo, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.PriceHedging GetPriceHedging(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetPriceHedging(supplier, agreementNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.PriceHedging> GetPriceHedgingAsync(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetPriceHedgingAsync(supplier, agreementNumber, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.Agreement[] GetAgreementList(string supplier, string ticket) {
            return base.Channel.GetAgreementList(supplier, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetAgreementListAsync(string supplier, string ticket) {
            return base.Channel.GetAgreementListAsync(supplier, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.Agreement[] GetFarmingAgreementList(string supplier, string ticket) {
            return base.Channel.GetFarmingAgreementList(supplier, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement[]> GetFarmingAgreementListAsync(string supplier, string ticket) {
            return base.Channel.GetFarmingAgreementListAsync(supplier, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.Agreement GetAgreement(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetAgreement(supplier, agreementNumber, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.Agreement> GetAgreementAsync(string supplier, string agreementNumber, string ticket) {
            return base.Channel.GetAgreementAsync(supplier, agreementNumber, ticket);
        }
        
        public Gro.Core.DataModels.AgreementDtos.DryAgreement[] GetDryAgreementList(string supplier, string ticket) {
            return base.Channel.GetDryAgreementList(supplier, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.AgreementDtos.DryAgreement[]> GetDryAgreementListAsync(string supplier, string ticket) {
            return base.Channel.GetDryAgreementListAsync(supplier, ticket);
        }
    }
}
