//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gro.Infrastructure.Data.PurchasingAgreementService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PurchasingAgreementService.IPurchasingAgreementService")]
    public interface IPurchasingAgreementService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/Ping", ReplyAction="http://tempuri.org/IPurchasingAgreementService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/Ping", ReplyAction="http://tempuri.org/IPurchasingAgreementService/PingResponse")]
        System.Threading.Tasks.Task<bool> PingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/DeletePriceWatch", ReplyAction="http://tempuri.org/IPurchasingAgreementService/DeletePriceWatchResponse")]
        bool DeletePriceWatch(int Id, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/DeletePriceWatch", ReplyAction="http://tempuri.org/IPurchasingAgreementService/DeletePriceWatchResponse")]
        System.Threading.Tasks.Task<bool> DeletePriceWatchAsync(int Id, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetCustomer", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetCustomerResponse")]
        Gro.Core.DataModels.PurchasingAgreements.Customer GetCustomer(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetCustomer", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetCustomerResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Customer> GetCustomerAsync(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetDryingAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetDryingAgreementResponse")]
        Gro.Core.DataModels.PurchasingAgreements.DryingAgreement GetDryingAgreement(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetDryingAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetDryingAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.DryingAgreement> GetDryingAgreementAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesPoolAgreementResponse" +
            "")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesPoolAgreement(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesPoolAgreementResponse" +
            "")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesPoolAgreementAsync(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesSpotAndForwardAgreeme" +
            "nt", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesSpotAndForwardAgreeme" +
            "ntResponse")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesSpotAndForwardAgreement(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesSpotAndForwardAgreeme" +
            "nt", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesSpotAndForwardAgreeme" +
            "ntResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesSpotAndForwardAgreementAsync(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsSpotAndForwardAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsSpotAndForwardAgreementR" +
            "esponse")]
        System.Collections.Generic.Dictionary<string, string> GetPeriodsSpotAndForwardAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsSpotAndForwardAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsSpotAndForwardAgreementR" +
            "esponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsSpotAndForwardAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesStorageAgreementRespo" +
            "nse")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesStorageAgreement(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetGrainTypesStorageAgreementRespo" +
            "nse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesStorageAgreementAsync(string productItemId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryPoolAgreementRes" +
            "ponse")]
        System.Collections.Generic.Dictionary<int, string> GetModesOfDeliveryPoolAgreement(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryPoolAgreementRes" +
            "ponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliveryPoolAgreementAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryStorageAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryStorageAgreement" +
            "Response")]
        System.Collections.Generic.Dictionary<int, string> GetModesOfDeliveryStorageAgreement(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryStorageAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliveryStorageAgreement" +
            "Response")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliveryStorageAgreementAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliverySpotAndForwardAg" +
            "reement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliverySpotAndForwardAg" +
            "reementResponse")]
        System.Collections.Generic.Dictionary<int, string> GetModesOfDeliverySpotAndForwardAgreement(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliverySpotAndForwardAg" +
            "reement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetModesOfDeliverySpotAndForwardAg" +
            "reementResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliverySpotAndForwardAgreementAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPoolAgreementResponse")]
        System.Collections.Generic.Dictionary<string, string> GetPeriodsPoolAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPoolAgreementResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsPoolAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPriceProtectingStorageAg" +
            "reement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPriceProtectingStorageAg" +
            "reementResponse")]
        System.Collections.Generic.Dictionary<string, string> GetPeriodsPriceProtectingStorageAgreement(string priceAreaId, string productItemId, string grainType, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPriceProtectingStorageAg" +
            "reement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsPriceProtectingStorageAg" +
            "reementResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsPriceProtectingStorageAgreementAsync(string priceAreaId, string productItemId, string grainType, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsStorageAgreementResponse" +
            "")]
        System.Collections.Generic.Dictionary<string, string> GetPeriodsStorageAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPeriodsStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPeriodsStorageAgreementResponse" +
            "")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsStorageAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceAreaDescr", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceAreaDescrResponse")]
        string GetPriceAreaDescr(string priceAreaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceAreaDescr", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceAreaDescrResponse")]
        System.Threading.Tasks.Task<string> GetPriceAreaDescrAsync(string priceAreaId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceAreas", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceAreasResponse")]
        Gro.Core.DataModels.PurchasingAgreements.PriceArea[] GetPriceAreas(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceAreas", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceAreasResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PriceArea[]> GetPriceAreasAsync(string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPricePeriodsGrainPrice", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPricePeriodsGrainPriceResponse")]
        Gro.Core.DataModels.PurchasingAgreements.PricePeriod[] GetPricePeriodsGrainPrice(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPricePeriodsGrainPrice", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPricePeriodsGrainPriceResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PricePeriod[]> GetPricePeriodsGrainPriceAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceWatch", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceWatchResponse")]
        Gro.Core.DataModels.PurchasingAgreements.PriceWatch[] GetPriceWatch(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetPriceWatch", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetPriceWatchResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PriceWatch[]> GetPriceWatchAsync(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsPoolAgreementResponse")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsPoolAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsPoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsPoolAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsPoolAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsSpotAndForwardAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsSpotAndForwardAgreement" +
            "Response")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsSpotAndForwardAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsSpotAndForwardAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsSpotAndForwardAgreement" +
            "Response")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsSpotAndForwardAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsStorageAgreementRespons" +
            "e")]
        Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsStorageAgreement(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetProductsStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetProductsStorageAgreementRespons" +
            "e")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsStorageAgreementAsync(string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementsForPriceProtec" +
            "tion", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementsForPriceProtec" +
            "tionResponse")]
        Gro.Core.DataModels.PurchasingAgreements.StorageAgreement[] GetStorageAgreementsForPriceProtection(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementsForPriceProtec" +
            "tion", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementsForPriceProtec" +
            "tionResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.StorageAgreement[]> GetStorageAgreementsForPriceProtectionAsync(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementValuesForPriceP" +
            "rotection", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementValuesForPriceP" +
            "rotectionResponse")]
        Gro.Core.DataModels.PurchasingAgreements.StorageAgreement GetStorageAgreementValuesForPriceProtection(string agreementId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementValuesForPriceP" +
            "rotection", ReplyAction="http://tempuri.org/IPurchasingAgreementService/GetStorageAgreementValuesForPriceP" +
            "rotectionResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.StorageAgreement> GetStorageAgreementValuesForPriceProtectionAsync(string agreementId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveCustomerFavoritePriceArea", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveCustomerFavoritePriceAreaRespo" +
            "nse")]
        bool SaveCustomerFavoritePriceArea(string customerId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveCustomerFavoritePriceArea", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveCustomerFavoritePriceAreaRespo" +
            "nse")]
        System.Threading.Tasks.Task<bool> SaveCustomerFavoritePriceAreaAsync(string customerId, string priceAreaId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveDryingAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveDryingAgreementResponse")]
        string SaveDryingAgreement(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveDryingAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveDryingAgreementResponse")]
        System.Threading.Tasks.Task<string> SaveDryingAgreementAsync(string customerId, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SavePoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SavePoolAgreementResponse")]
        Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SavePoolAgreement(Gro.Core.DataModels.PurchasingAgreements.PoolAgreement agreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SavePoolAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SavePoolAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SavePoolAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.PoolAgreement agreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SavePriceProtectedStorageAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SavePriceProtectedStorageAgreement" +
            "Response")]
        Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SavePriceProtectedStorageAgreement(Gro.Core.DataModels.PurchasingAgreements.PriceProtectStorageAgreement storageAgreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SavePriceProtectedStorageAgreement" +
            "", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SavePriceProtectedStorageAgreement" +
            "Response")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SavePriceProtectedStorageAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.PriceProtectStorageAgreement storageAgreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveSpotAndForwardAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveSpotAndForwardAgreementRespons" +
            "e")]
        Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SaveSpotAndForwardAgreement(Gro.Core.DataModels.PurchasingAgreements.SpotAndForwardAgreement agreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveSpotAndForwardAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveSpotAndForwardAgreementRespons" +
            "e")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SaveSpotAndForwardAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.SpotAndForwardAgreement agreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveStorageAgreementResponse")]
        Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SaveStorageAgreement(Gro.Core.DataModels.PurchasingAgreements.StorageAgreement storageAgreement, string ticket);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPurchasingAgreementService/SaveStorageAgreement", ReplyAction="http://tempuri.org/IPurchasingAgreementService/SaveStorageAgreementResponse")]
        System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SaveStorageAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.StorageAgreement storageAgreement, string ticket);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPurchasingAgreementServiceChannel : Gro.Infrastructure.Data.PurchasingAgreementService.IPurchasingAgreementService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PurchasingAgreementServiceClient : System.ServiceModel.ClientBase<Gro.Infrastructure.Data.PurchasingAgreementService.IPurchasingAgreementService>, Gro.Infrastructure.Data.PurchasingAgreementService.IPurchasingAgreementService {
        
        public PurchasingAgreementServiceClient() {
        }
        
        public PurchasingAgreementServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PurchasingAgreementServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingAgreementServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PurchasingAgreementServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public System.Threading.Tasks.Task<bool> PingAsync() {
            return base.Channel.PingAsync();
        }
        
        public bool DeletePriceWatch(int Id, string ticket) {
            return base.Channel.DeletePriceWatch(Id, ticket);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePriceWatchAsync(int Id, string ticket) {
            return base.Channel.DeletePriceWatchAsync(Id, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Customer GetCustomer(string customerId, string ticket) {
            return base.Channel.GetCustomer(customerId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Customer> GetCustomerAsync(string customerId, string ticket) {
            return base.Channel.GetCustomerAsync(customerId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.DryingAgreement GetDryingAgreement(string ticket) {
            return base.Channel.GetDryingAgreement(ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.DryingAgreement> GetDryingAgreementAsync(string ticket) {
            return base.Channel.GetDryingAgreementAsync(ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesPoolAgreement(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesPoolAgreement(productItemId, priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesPoolAgreementAsync(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesPoolAgreementAsync(productItemId, priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesSpotAndForwardAgreement(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesSpotAndForwardAgreement(productItemId, priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesSpotAndForwardAgreementAsync(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesSpotAndForwardAgreementAsync(productItemId, priceAreaId, ticket);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetPeriodsSpotAndForwardAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsSpotAndForwardAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsSpotAndForwardAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsSpotAndForwardAgreementAsync(priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetGrainTypesStorageAgreement(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesStorageAgreement(productItemId, priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetGrainTypesStorageAgreementAsync(string productItemId, string priceAreaId, string ticket) {
            return base.Channel.GetGrainTypesStorageAgreementAsync(productItemId, priceAreaId, ticket);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetModesOfDeliveryPoolAgreement(string ticket) {
            return base.Channel.GetModesOfDeliveryPoolAgreement(ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliveryPoolAgreementAsync(string ticket) {
            return base.Channel.GetModesOfDeliveryPoolAgreementAsync(ticket);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetModesOfDeliveryStorageAgreement(string ticket) {
            return base.Channel.GetModesOfDeliveryStorageAgreement(ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliveryStorageAgreementAsync(string ticket) {
            return base.Channel.GetModesOfDeliveryStorageAgreementAsync(ticket);
        }
        
        public System.Collections.Generic.Dictionary<int, string> GetModesOfDeliverySpotAndForwardAgreement(string ticket) {
            return base.Channel.GetModesOfDeliverySpotAndForwardAgreement(ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> GetModesOfDeliverySpotAndForwardAgreementAsync(string ticket) {
            return base.Channel.GetModesOfDeliverySpotAndForwardAgreementAsync(ticket);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetPeriodsPoolAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsPoolAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsPoolAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsPoolAgreementAsync(priceAreaId, ticket);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetPeriodsPriceProtectingStorageAgreement(string priceAreaId, string productItemId, string grainType, string ticket) {
            return base.Channel.GetPeriodsPriceProtectingStorageAgreement(priceAreaId, productItemId, grainType, ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsPriceProtectingStorageAgreementAsync(string priceAreaId, string productItemId, string grainType, string ticket) {
            return base.Channel.GetPeriodsPriceProtectingStorageAgreementAsync(priceAreaId, productItemId, grainType, ticket);
        }
        
        public System.Collections.Generic.Dictionary<string, string> GetPeriodsStorageAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsStorageAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>> GetPeriodsStorageAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetPeriodsStorageAgreementAsync(priceAreaId, ticket);
        }
        
        public string GetPriceAreaDescr(string priceAreaId) {
            return base.Channel.GetPriceAreaDescr(priceAreaId);
        }
        
        public System.Threading.Tasks.Task<string> GetPriceAreaDescrAsync(string priceAreaId) {
            return base.Channel.GetPriceAreaDescrAsync(priceAreaId);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.PriceArea[] GetPriceAreas(string ticket) {
            return base.Channel.GetPriceAreas(ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PriceArea[]> GetPriceAreasAsync(string ticket) {
            return base.Channel.GetPriceAreasAsync(ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.PricePeriod[] GetPricePeriodsGrainPrice(string priceAreaId, string ticket) {
            return base.Channel.GetPricePeriodsGrainPrice(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PricePeriod[]> GetPricePeriodsGrainPriceAsync(string priceAreaId, string ticket) {
            return base.Channel.GetPricePeriodsGrainPriceAsync(priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.PriceWatch[] GetPriceWatch(string customerId, string ticket) {
            return base.Channel.GetPriceWatch(customerId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.PriceWatch[]> GetPriceWatchAsync(string customerId, string ticket) {
            return base.Channel.GetPriceWatchAsync(customerId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsPoolAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetProductsPoolAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsPoolAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetProductsPoolAgreementAsync(priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsSpotAndForwardAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetProductsSpotAndForwardAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsSpotAndForwardAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetProductsSpotAndForwardAgreementAsync(priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.Product[] GetProductsStorageAgreement(string priceAreaId, string ticket) {
            return base.Channel.GetProductsStorageAgreement(priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.Product[]> GetProductsStorageAgreementAsync(string priceAreaId, string ticket) {
            return base.Channel.GetProductsStorageAgreementAsync(priceAreaId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.StorageAgreement[] GetStorageAgreementsForPriceProtection(string customerId, string ticket) {
            return base.Channel.GetStorageAgreementsForPriceProtection(customerId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.StorageAgreement[]> GetStorageAgreementsForPriceProtectionAsync(string customerId, string ticket) {
            return base.Channel.GetStorageAgreementsForPriceProtectionAsync(customerId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.StorageAgreement GetStorageAgreementValuesForPriceProtection(string agreementId, string ticket) {
            return base.Channel.GetStorageAgreementValuesForPriceProtection(agreementId, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.StorageAgreement> GetStorageAgreementValuesForPriceProtectionAsync(string agreementId, string ticket) {
            return base.Channel.GetStorageAgreementValuesForPriceProtectionAsync(agreementId, ticket);
        }
        
        public bool SaveCustomerFavoritePriceArea(string customerId, string priceAreaId, string ticket) {
            return base.Channel.SaveCustomerFavoritePriceArea(customerId, priceAreaId, ticket);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomerFavoritePriceAreaAsync(string customerId, string priceAreaId, string ticket) {
            return base.Channel.SaveCustomerFavoritePriceAreaAsync(customerId, priceAreaId, ticket);
        }
        
        public string SaveDryingAgreement(string customerId, string ticket) {
            return base.Channel.SaveDryingAgreement(customerId, ticket);
        }
        
        public System.Threading.Tasks.Task<string> SaveDryingAgreementAsync(string customerId, string ticket) {
            return base.Channel.SaveDryingAgreementAsync(customerId, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SavePoolAgreement(Gro.Core.DataModels.PurchasingAgreements.PoolAgreement agreement, string ticket) {
            return base.Channel.SavePoolAgreement(agreement, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SavePoolAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.PoolAgreement agreement, string ticket) {
            return base.Channel.SavePoolAgreementAsync(agreement, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SavePriceProtectedStorageAgreement(Gro.Core.DataModels.PurchasingAgreements.PriceProtectStorageAgreement storageAgreement, string ticket) {
            return base.Channel.SavePriceProtectedStorageAgreement(storageAgreement, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SavePriceProtectedStorageAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.PriceProtectStorageAgreement storageAgreement, string ticket) {
            return base.Channel.SavePriceProtectedStorageAgreementAsync(storageAgreement, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SaveSpotAndForwardAgreement(Gro.Core.DataModels.PurchasingAgreements.SpotAndForwardAgreement agreement, string ticket) {
            return base.Channel.SaveSpotAndForwardAgreement(agreement, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SaveSpotAndForwardAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.SpotAndForwardAgreement agreement, string ticket) {
            return base.Channel.SaveSpotAndForwardAgreementAsync(agreement, ticket);
        }
        
        public Gro.Core.DataModels.PurchasingAgreements.AgreementResponse SaveStorageAgreement(Gro.Core.DataModels.PurchasingAgreements.StorageAgreement storageAgreement, string ticket) {
            return base.Channel.SaveStorageAgreement(storageAgreement, ticket);
        }
        
        public System.Threading.Tasks.Task<Gro.Core.DataModels.PurchasingAgreements.AgreementResponse> SaveStorageAgreementAsync(Gro.Core.DataModels.PurchasingAgreements.StorageAgreement storageAgreement, string ticket) {
            return base.Channel.SaveStorageAgreementAsync(storageAgreement, ticket);
        }
    }
}
